defaults: &defaults
  sources_storage_path: /tmp
  problems_path: /tmp/problems
  sandbox_path: /usr/bin/taker
  exec_pool: /tmp
  compiler_options: '-lm -fno-asm -ansi -DONLINE_JUDGE -O2 -static'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults